In [1]:
matrix1 = [[1,2,3] , [4,5,6]]
matrix2 = [[7,8,9] , [10,11,12]]
result = [[0,0,0] , [0,0,0]]

for i in range(len(matrix1)) :
    for j in range(len(matrix1[0])) :
        result[i][j] = matrix1[i][j] + matrix2[i][j]

print("matrix1 = " , matrix1)
print("matrix2 = " , matrix2 , "\n")

print("sum of matrix 1 and matrix2:")
print(result)

matrix1 =  [[1, 2, 3], [4, 5, 6]]
matrix2 =  [[7, 8, 9], [10, 11, 12]] 

sum of matrix 1 and matrix2:
[[8, 10, 12], [14, 16, 18]]


In [4]:
import numpy as np

matrix1 = np.array([[1,2,3] , [4,5,6]])
matrix2 = np.array([[7,8,9] , [10,11,12]])
res = matrix1+matrix2
print("matrix1 = " , matrix1)
print("matrix2 = " , matrix2 , "\n")

print("sum of matrix 1 and matrix2:")
print(res)

matrix1 =  [[1 2 3]
 [4 5 6]]
matrix2 =  [[ 7  8  9]
 [10 11 12]] 

sum of matrix 1 and matrix2:
[[ 8 10 12]
 [14 16 18]]
